server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://10.10.1.119:3306/yiworld?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  level:
    root: debug