# Spring boot application
spring:
  application:
    name: myshop-service-upload
server:
  port: 8888

fastdfs.base.url: http://10.10.1.163:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 10.10.1.163:22122